DROP TABLE EMPLOYEES;
DROP TABLE EVENTS;
DROP TABLE ASSIGNMENTS;

CREATE TABLE EMPLOYEES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    contact INTEGER NOT NULL,
    email TEXT NOT NULL
);

CREATE TABLE EVENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    location TEXT NOT NULL,
    date TEXT NOT NULL,
    client_name TEXT NOT NULL,
    client_contact TEXT,
    client_email TEXT
);

CREATE TABLE ASSIGNMENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    emp_id INTEGER REFERENCES EMPLOYEES (id) ON DELETE CASCADE ON UPDATE CASCADE,
    event_id INTEGER REFERENCES EVENTS (id) ON DELETE CASCADE ON UPDATE CASCADE,
    date TEXT NOT NULL UNIQUE
);
